
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Master].[VIEWREQUEST_PROCESS_MASTER](
	[PROCESS_CODE] [tinyint] NOT NULL,
	[PROCESS_NAME] [varchar](128) NULL,
	[PROCESS_SHORT_CODE] [varchar](16) NULL,
	[DISPLAY_ORDER] [tinyint] NULL,
	[PROCESS_DEPARTMENT_CODE] [tinyint] NULL,
	[IS_ACTIVE] [bit] NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[ROW_VERSION] [timestamp] NOT NULL,
	[DATA_VERSION] [bigint] NULL,
 CONSTRAINT [PK_PROCESS_MASTER] PRIMARY KEY CLUSTERED 
(
	[PROCESS_CODE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
)
GO

ALTER TABLE [Master].[VIEWREQUEST_PROCESS_MASTER] ADD  CONSTRAINT [DF_VIEWREQUEST_PROCESS_MASTER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [Master].[VIEWREQUEST_PROCESS_MASTER] ADD  CONSTRAINT [DF_VIEWREQUEST_PROCESS_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Master].[VIEWREQUEST_PROCESS_MASTER] ADD  DEFAULT ((0)) FOR [DATA_VERSION]
GO


ALTER TABLE [Master].[VIEWREQUEST_PROCESS_MASTER]  WITH CHECK ADD  CONSTRAINT [FK_VIEWREQUEST_PROCESS_MASTER_DEPARTMENT_MASTER] FOREIGN KEY([PROCESS_DEPARTMENT_CODE])
REFERENCES [Master].[DEPARTMENT_MASTER] ([DEPARTMENT_CODE])
GO

ALTER TABLE [Master].[VIEWREQUEST_PROCESS_MASTER] CHECK CONSTRAINT [FK_VIEWREQUEST_PROCESS_MASTER_DEPARTMENT_MASTER]
GO


EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'View Request Process Master Like What Intention of Person To View Stone' , @level0type=N'SCHEMA',@level0name=N'Master', @level1type=N'TABLE',@level1name=N'VIEWREQUEST_PROCESS_MASTER'
GO


