
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Master].[REASON_MASTER](
	[REASON_CODE] [tinyint] NOT NULL,
	[REASON_NAME] [varchar](128) NULL,
	[DISPLAY_ORDER] [tinyint] NULL,
	[IS_ACTIVE] [bit] NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[ROW_VERSION] [timestamp] NOT NULL,
	[DATA_VERSION] [bigint] NULL,
 CONSTRAINT [PK_REASON_MASTER] PRIMARY KEY CLUSTERED 
(
	[REASON_CODE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
)
GO

ALTER TABLE [Master].[REASON_MASTER] ADD  CONSTRAINT [DF_REASON_MASTER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [Master].[REASON_MASTER] ADD  CONSTRAINT [DF_REASON_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Master].[REASON_MASTER] ADD  DEFAULT ((0)) FOR [DATA_VERSION]
GO


EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Reason Master' , @level0type=N'SCHEMA',@level0name=N'Master', @level1type=N'TABLE',@level1name=N'REASON_MASTER'
GO


