

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Packet].[SUB_TRN_PROCESS_MASTER](
	[SUB_PROCESS_ID] BIGINT NOT NULL IDENTITY(1, 1),
	[PROCESS_ID] BIGINT NOT NULL,
	[STONEID] BIGINT NOT NULL,
	[USER_CODE] SMALLINT NOT NULL,
	[USER_ISSUE_DATETIME] DATETIME NOT NULL,
	[USER_RECEIVE_DATETIME] DATETIME NOT NULL,
	[ISSUE_USER_CODE] SMALLINT NOT NULL,
	[RECEIVE_USER_CODE] SMALLINT NOT NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[ROW_VERSION] [timestamp] NOT NULL,
	[DATA_VERSION] [bigint] NULL,
 CONSTRAINT [PK_SUB_TRN_PROCESS_MASTER] PRIMARY KEY CLUSTERED 
(
	[SUB_PROCESS_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
)
GO

ALTER TABLE [Packet].[SUB_TRN_PROCESS_MASTER] ADD  CONSTRAINT [DF_SUB_TRN_PROCESS_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Packet].[SUB_TRN_PROCESS_MASTER] ADD  DEFAULT ((0)) FOR [DATA_VERSION]
GO

ALTER TABLE [Packet].[SUB_TRN_PROCESS_MASTER] ADD CONSTRAINT [FK_SUB_TRN_PROCESS_MASTER_TRN_PROCESS_MASTER] FOREIGN KEY ([PROCESS_ID]) REFERENCES [Packet].[TRN_PROCESS_MASTER] ([PROCESS_ID])
GO

ALTER TABLE [Packet].[SUB_TRN_PROCESS_MASTER] ADD CONSTRAINT [FK_SUB_TRN_PROCESS_MASTER_ISSUE_USER_MASTER] FOREIGN KEY ([ISSUE_USER_CODE]) REFERENCES [Master].[USER_MASTER] ([USER_CODE])
GO

ALTER TABLE [Packet].[SUB_TRN_PROCESS_MASTER] ADD CONSTRAINT [FK_SUB_TRN_PROCESS_MASTER_RECEIVE_USER_MASTER] FOREIGN KEY ([RECEIVE_USER_CODE]) REFERENCES [Master].[USER_MASTER] ([USER_CODE])
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Employee Transfer Entry With in Same Department' , @level0type=N'SCHEMA',@level0name=N'Packet', @level1type=N'TABLE',@level1name=N'SUB_TRN_PROCESS_MASTER'
GO


