
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Master].[SUB_INCLUSION_TYPE_MASTER](
	[SUB_INCLUSION_TYPE_CODE] [tinyint] NOT NULL,
	[SUB_INCLUSION_TYPE_NAME] [varchar](128) NULL,
	[DISPLAY_ORDER] [tinyint] NULL,
	[IS_ACTIVE] [bit] NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[ROW_VERSION] [timestamp] NOT NULL,
	[DATA_VERSION] [bigint] NULL,
 CONSTRAINT [PK_SUB_INCLUSION_TYPE] PRIMARY KEY CLUSTERED 
(
	[SUB_INCLUSION_TYPE_CODE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
)
GO

ALTER TABLE [Master].[SUB_INCLUSION_TYPE_MASTER] ADD  CONSTRAINT [DF_SUB_INCLUSION_TYPE_MASTER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [Master].[SUB_INCLUSION_TYPE_MASTER] ADD  CONSTRAINT [DF_SUB_INCLUSION_TYPE_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Master].[SUB_INCLUSION_TYPE_MASTER] ADD  DEFAULT ((0)) FOR [DATA_VERSION]
GO


EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Sub Inclusion Type Master it contain 1 As Sub Group And 2 As Location' , @level0type=N'SCHEMA',@level0name=N'Master', @level1type=N'TABLE',@level1name=N'SUB_INCLUSION_TYPE_MASTER'
GO


