USE [srk_db]
GO

/****** Object:  Table [Packet].[VENDOR_STONE_DETAILS]    Script Date: 15/01/2018 10:19:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Packet].[VENDOR_STONE_DETAILS](
	[PACKET_ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[STONEID] [VARCHAR](16) NOT NULL,
	[VENDOR_CODE] [SMALLINT] NULL,
	[CARRIER_CODE] [SMALLINT] NULL,
	[OUTWARD_DATETIME] [DATETIME] NULL,
	[INWARD_USER_CODE] [SMALLINT] NULL,
	[SMARTI_USER_CODE] [SMALLINT] NULL,
	[SMARTI_DATETIME] [DATETIME] NULL,
	[GROUP_NUMBER] [VARCHAR](20) NULL,
	[CERTIFICATE_CODE] [TINYINT] NULL,
	[CERTIFICATE_NO] [VARCHAR](16) NULL,
	[VENDOR_STONEID] [VARCHAR](64) NULL,
	[VENDOR_LOT_CODE] [VARCHAR](8) NULL,
	[VENDOR_SERIAL_NO] [SMALLINT] NULL,
	[ISSUE_CARAT] [NUMERIC](8, 3) NULL,
	[SHAPE_CODE] [TINYINT] NOT NULL,
	[CLARITY_CODE] [TINYINT] NOT NULL,
	[CLARITY_SIGN] [VARCHAR](4) NULL,
	[COLOR_CODE] [TINYINT] NOT NULL,
	[COLOR_SIGN] [VARCHAR](4) NULL,
	[CUT_CODE] [TINYINT] NULL,
	[POLISH_CODE] [TINYINT] NULL,
	[SYMMETRY_CODE] [TINYINT] NULL,
	[FLUORESCENCE_CODE] [TINYINT] NULL,

	[INCLUSION_CODE1] [INT] NULL,
	[TABLE_BLACK_INCLUSION_CODE] [INT] NULL,
	[TABLE_OPEN_INCLUSION_CODE] [INT] NULL,
	[TABLE_SPOT_INCLUSION_CODE] [INT] NULL,
	[TABLE_EXTRAFACET_CODE] [INT] NULL,
	[SIDE_INCLUSION_CODE] [INT] NULL,
	[SIDE_BLACK_INCLUSION_CODE] [INT] NULL,
	[SIDE_SPOT_INCLUSION_CODE] [INT] NULL,
	[CROWN_OPEN_INCLUSION_CODE] [INT] NULL,
	[PAVILION_EXTRAFACET_CODE] [INT] NULL,
	[PAVILION_OPEN_INCLUSION_CODE] [INT] NULL,
	[GIRDLE_OPEN_INCLUSION_CODE] [INT] NULL,
	[LUSTER_CODE] [TINYINT] NULL,
	[BROWN_CODE] [INT] NULL,
	[NATURAL_INCLUSION_CODE] [INT] NULL,
	[GIRDLE_INCLUSION_CODE] [INT] NULL,
	[OPEN_WINDOW_INCLUSION_CODE] [INT] NULL,
	[CULET_CODE] [INT] NULL,
	
	[HEART_ARROW_CODE] [INT] NULL,
	[IS_EYE_CLEAN] [BIT] NULL,
	[LOCATION_CODE] [INT] NULL,
	[DIAMETER_RATIO] [INT] NULL,
	[MINIMUM_DIAMETER_LENGTH] [NUMERIC](8, 2) NULL,
	[MAXIMUM_DIAMETER_LENGTH] [NUMERIC](8, 2) NULL,
	[TOTAL_DEPTH] [NUMERIC](8, 2) NULL,
	[TABLED] [NUMERIC](8, 2) NULL,
	[HEIGHT] [NUMERIC](8, 2) NULL,
	[MEASUREMENT] [VARCHAR](16) NULL,
	[CROWN_ANGLE] [NUMERIC](8, 2) NULL,
	[CROWN_HEIGHT] [NUMERIC](8, 2) NULL,
	[PAVALION_ANGLE] [NUMERIC](8, 2) NULL,
	[PAVALION_HEIGHT] [NUMERIC](8, 2) NULL,
	[STAR_LENGTH] [NUMERIC](8, 2) NULL,
	[LOWER_HALF] [NUMERIC](8, 2) NULL,
	[GIRDLE] [NUMERIC](8, 2) NULL,
	[GIRDLE_CODE] [TINYINT] NULL,
	[TO_GIRDLE_CODE] [TINYINT] NULL,
	[LAB_COMMENT_CODE] [TINYINT] NULL,
	[LAB_CONTROL_NO] [NUMERIC](8, 0) NULL,
	[RFID_TAG] [VARCHAR](16) NULL,
	[DOLLAR_RRATE] [NUMERIC](9, 2) NULL,
	[DOLLAR_PERCENTAGE] [NUMERIC](8, 3) NULL,
	[PACKET_ROUGH_RATE] [NUMERIC](9, 2) NULL,
	[PACEKT_RATE] [NUMERIC](9, 2) NULL,
	[PACKET_PERCENTAGE] [NUMERIC](8, 3) NULL,
	[ORIGINAL_RATE] [NUMERIC](9, 2) NULL,
	[ORIGINAL_PERCENTAGE] [NUMERIC](8, 3) NULL,
	[COST_RATE] [NUMERIC](9, 2) NULL,
	[COST_PERERCENTAGE] [NUMERIC](8, 3) NULL,
	[SYSTEM_RATE] [NUMERIC](9, 2) NULL,
	[SYSTEM_PERCENTAGE] [NUMERIC](8, 3) NULL,
	[IS_ORDER_CONFIRM] [BIT] NULL,
	[IS_ORDER_MISSED] [BIT] NULL,
	[ORDER_NO] [SMALLINT] NULL,
	[IS_STOCK_INWARD] [BIT] NULL,
	[INWARD_DATETIME] [DATETIME] NULL,
	[IS_GRADING_VERIFY] [BIT] NULL,
	[VENDOR_EXPORTDATE] [DATE] NULL,
	[VENDOR_COMPNAME] [VARCHAR](100) NULL,
	[OPEREMARK] [VARCHAR](800) NULL,
	[MINES_NAME] [VARCHAR](30) NULL,
	[PARCEL_ID] [INT] NULL,
	[INVOICE_ID] [INT] NULL,
	[ROUGH_CARAT] [NUMERIC](8, 3) NULL,
	[MAKABLE_CARAT] [NUMERIC](8, 3) NULL,
	[REMARK] [VARCHAR](256) NULL,
	[SUB_ORDERNO] [SMALLINT] NULL,
	[IS_FM_ELIGIBLE] [BIT] NULL,
	[IS_CM_ELIGIBLE] [BIT] NULL,
	[RAP_YEAR_MONTH] [TINYINT] NULL,
	[RAP_NUMBER] [SMALLINT] NULL,
	[CLV_LOT_CODE] [VARCHAR](5) NULL,
	[CLV_SERIAL_NUMBER] [INT] NULL,
	[CLV_TAG] [VARCHAR](4) NULL,
	[GIA_ROUGH_REPORT_NO] [VARCHAR](10) NULL,
	[APPS_CODE] [TINYINT] NULL,
	[CREATED_DATETIME] [DATETIME] NULL,
	[CREATED_BY] [SMALLINT] NULL,
	[CREATED_IPLOCATION_ID] [INT] NULL,
	[MODIFIED_DATETIME] [DATETIME] NULL,
	[MODIFIED_BY] [SMALLINT] NULL,
	[MODIFIED_IPLOCATION_ID] [INT] NULL,
	[ROW_VERSION] [TIMESTAMP] NOT NULL,
	[DATA_VERSION] [BIGINT] NULL,
 CONSTRAINT [PK_VENDOR_STONE_DETAILS] PRIMARY KEY CLUSTERED 
(
	[PACKET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_ISSUE_CARAT]  DEFAULT ((0)) FOR [ISSUE_CARAT]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_MINIMUM_DIAMETER_LENGTH]  DEFAULT ((0)) FOR [MINIMUM_DIAMETER_LENGTH]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_MAXIMUM_DIAMETER_LENGTH]  DEFAULT ((0)) FOR [MAXIMUM_DIAMETER_LENGTH]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_TOTAL_DEPTH]  DEFAULT ((0)) FOR [TOTAL_DEPTH]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_TABLED]  DEFAULT ((0)) FOR [TABLED]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_HEIGHT]  DEFAULT ((0)) FOR [HEIGHT]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_MEASUREMENT]  DEFAULT ('') FOR [MEASUREMENT]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_CROWN_ANGLE]  DEFAULT ((0)) FOR [CROWN_ANGLE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_PAVALION_ANGLE]  DEFAULT ((0)) FOR [PAVALION_ANGLE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_PAVALION_HEIGHT]  DEFAULT ((0)) FOR [PAVALION_HEIGHT]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_STAR_LENGTH]  DEFAULT ((0)) FOR [STAR_LENGTH]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_LOWER_HALF]  DEFAULT ((0)) FOR [LOWER_HALF]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_GIRDLE]  DEFAULT ((0)) FOR [GIRDLE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_DRATE]  DEFAULT ((0)) FOR [DOLLAR_RRATE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_DPER]  DEFAULT ((0)) FOR [DOLLAR_PERCENTAGE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_PRRATE]  DEFAULT ((0)) FOR [PACKET_ROUGH_RATE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_PRATEP]  DEFAULT ((0)) FOR [PACEKT_RATE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_PACKET_PERCENTAGE]  DEFAULT ((0)) FOR [PACKET_PERCENTAGE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_ORIGINAL_RATE]  DEFAULT ((0)) FOR [ORIGINAL_RATE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_ORIGINAL_PERCENTAGE]  DEFAULT ((0)) FOR [ORIGINAL_PERCENTAGE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_COST_RATE]  DEFAULT ((0)) FOR [COST_RATE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_COST_PERERCENTAGE]  DEFAULT ((0)) FOR [COST_PERERCENTAGE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_SYSTEM_RATE]  DEFAULT ((0)) FOR [SYSTEM_RATE]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF_VENDOR_STONE_DETAILS_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Packet].[VENDOR_STONE_DETAILS] ADD  CONSTRAINT [DF__VENDOR_ST__DATA___6CCE0729]  DEFAULT ((0)) FOR [DATA_VERSION]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'This Table use to Store information of Diamond Come from Vendor Waiting for Input in Stock or Market' , @level0type=N'SCHEMA',@level0name=N'Packet', @level1type=N'TABLE',@level1name=N'VENDOR_STONE_DETAILS'
GO


