USE [srk_db]
GO
/****** Object:  StoredProcedure [Stock].[USP_APPOINTMENT_SAVE]    Script Date: 30/01/2018 12:24:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:  Apexa Patel
-- Create date: 10-01-2018
-- Description: This storage procedure store appoint data
-- =============================================


ALTER PROCEDURE [Stock].[USP_APPOINTMENT_SAVE]
@PARTY_CODE 					INT,
@VISIT_DATE 					DATETIME,
@VISIT_FROM_TIME 				TIME,
@VISIT_TO_TIME 				TIME,
@IS_ACTIVE 					BIT,
@STONEID 						Stock.STONEID READONLY,
@VISIT_CONTACTS_DETAILS 		Stock.VISIT_CONTACTS_DETAILS READONLY,
@SECTION_ID 					SMALLINT,
@REMARK_TEXT 					Stock.REMARK_TEXT READONLY,
@VISIT_CONTACTS_KAM_DETAIL 	Stock.VISIT_CONTACTS_KAM_DETAIL READONLY,
@APPS_CODE 				 	TINYINT,
@USER_CODE 					SMALLINT, -- Code of logged in user who is adding/saving appointment
@CREATED_IPLOCATION_ID 		INT
AS
BEGIN

	DECLARE @IS_AUDIT BIT = 0
	SET @IS_AUDIT = (SELECT Audit.ALLOW_PERF_AUDIT())

	DECLARE @START_TIME DATETIME;
	 

	IF (@IS_AUDIT = 1)
	BEGIN
		SET @START_TIME = Master.Fn_GetISTDATETIME(); 
	END
 	
	DECLARE @VISIT_ID INT, @APPOINTMENT_ID INT = 0
	DECLARE @VISIT_CONTACT_ID INT, @WEEK_START_DATE DATETIME, @WEEK_END_DATE DATETIME
	
	SELECT @WEEK_START_DATE = DATEADD(DAY, 2 - 5, @VISIT_DATE), @WEEK_END_DATE=DATEADD(DAY, 8 - 5, @VISIT_DATE)

	SELECT @APPOINTMENT_ID = ISNULL((SELECT TOP 1 APPOINTMENT_ID FROM Stock.APPOINTMENT WHERE PARTY_CODE = @PARTY_CODE AND CREATED_DATETIME BETWEEN @WEEK_START_DATE AND @WEEK_END_DATE ),0) 

	IF (@APPOINTMENT_ID = 0)
	BEGIN
		SELECT @APPOINTMENT_ID = (ISNULL((SELECT MAX(APPOINTMENT_ID) FROM Stock.APPOINTMENT WHERE PARTY_CODE=@PARTY_CODE),0))+1
		
	INSERT INTO Stock.APPOINTMENT 
	(APPOINTMENT_ID, PARTY_CODE, APPS_CODE, CREATED_BY, CREATED_IPLOCATION_ID, MODIFIED_DATETIME, MODIFIED_BY, MODIFIED_IPLOCATION_ID) 	VALUES 
	(@APPOINTMENT_ID, @PARTY_CODE, @APPS_CODE, @USER_CODE, @CREATED_IPLOCATION_ID, Master.Fn_GetISTDATETIME(), @USER_CODE, @CREATED_IPLOCATION_ID)
	END

	INSERT INTO Stock.VISIT 
	(APPOINTMENT_ID, VISIT_DATE, VISIT_FROM_TIME, VISIT_TO_TIME, IS_ACTIVE, APPS_CODE, CREATED_BY, CREATED_IPLOCATION_ID, MODIFIED_DATETIME, MODIFIED_BY, MODIFIED_IPLOCATION_ID) 
	SELECT @APPOINTMENT_ID, @VISIT_DATE, @VISIT_FROM_TIME, @VISIT_TO_TIME, @IS_ACTIVE, @APPS_CODE, @USER_CODE, @CREATED_IPLOCATION_ID, Master.Fn_GetISTDATETIME(), @USER_CODE, @CREATED_IPLOCATION_ID
	
	SELECT @VISIT_ID = @@IDENTITY 

	INSERT INTO Stock.VISIT_DETAIL 
	(VISIT_ID, STONEID, SECTION_ID, SECTION_SLOT_FROM_TIME, SECTION_SLOT_TO_TIME, APPS_CODE, CREATED_BY, CREATED_IPLOCATION_ID, MODIFIED_DATETIME, MODIFIED_BY, MODIFIED_IPLOCATION_ID) 
	SELECT @VISIT_ID, STONEID, @SECTION_ID, @VISIT_FROM_TIME, @VISIT_TO_TIME, @APPS_CODE, @USER_CODE, @CREATED_IPLOCATION_ID, Master.Fn_GetISTDATETIME(), @USER_CODE, @CREATED_IPLOCATION_ID FROM @STONEID
	
	INSERT INTO Stock.VISIT_CONTACTS 
	(VISIT_ID, PARTY_CONTACTS_CODE, PARTY_ROLE_CODE, CONTACTS_LOCAL_COUNTRY_CODE, CONTACTS_LOCAL_PHONE_NUMBER, APPS_CODE, CREATED_BY, CREATED_IPLOCATION_ID, MODIFIED_DATETIME, MODIFIED_BY, MODIFIED_IPLOCATION_ID) 
	SELECT @VISIT_ID, PARTY_CONTACTS_CODE, PARTY_ROLE_CODE, CONTACTS_LOCAL_COUNTRY_CODE, CONTACTS_LOCAL_PHONE_NUMBER, @APPS_CODE, @USER_CODE, @CREATED_IPLOCATION_ID, Master.Fn_GetISTDATETIME(), @USER_CODE, @CREATED_IPLOCATION_ID FROM @VISIT_CONTACTS_DETAILS


	INSERT INTO Stock.VISIT_CONTACTS_KAM 
	(VISIT_CONTACTS_ID, PARTY_CONTACTS_KAM_CODE, APPS_CODE, CREATED_BY, CREATED_IPLOCATION_ID, MODIFIED_DATETIME, MODIFIED_BY, MODIFIED_IPLOCATION_ID) 
	SELECT vc.VISIT_CONTACTS_ID, vck.PARTY_CONTACTS_KAM_CODE, @APPS_CODE, @USER_CODE, @CREATED_IPLOCATION_ID, Master.Fn_GetISTDATETIME(), @USER_CODE, @CREATED_IPLOCATION_ID FROM @VISIT_CONTACTS_KAM_DETAIL vck LEFT OUTER JOIN Stock.VISIT_CONTACTS vc ON vc.PARTY_CONTACTS_CODE = vck.PARTY_CONTACTS_CODE WHERE vc.VISIT_ID = @VISIT_ID

	INSERT INTO Stock.REMARKS 
	(SOURCE_ID, REMARK_TEXT, REMARK_FROM, REMARK_TYPE_CODE, APPS_CODE, CREATED_BY, CREATED_IPLOCATION_ID, MODIFIED_DATETIME, MODIFIED_BY, MODIFIED_IPLOCATION_ID) 
	SELECT @VISIT_ID, REMARK_TEXT, @USER_CODE, (SELECT REMARK_TYPE_CODE FROM Master.REMARK_TYPE_MASTER WHERE REMARK_TYPE_KEY='appointment_remark'), @APPS_CODE, @USER_CODE, @CREATED_IPLOCATION_ID, Master.Fn_GetISTDATETIME(), @USER_CODE, @CREATED_IPLOCATION_ID FROM @REMARK_TEXT

	IF (@IS_AUDIT = 1)
	BEGIN
		INSERT INTO Audit.SP_PERF_AUDIT ( SP_NAME , START_TIME , END_TIME , EXECUTION_DURATION , APP_CODE )
		SELECT 'Stock.USP_APPOINTMENT_SAVE' , @start_time , Master.Fn_GetISTDATETIME() , Audit.DURATION(@start_time, Master.Fn_GetISTDATETIME()) , '13'; 
	END

END
